# Changes here will be overwritten by Copier
_commit: 1.0.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: eva.lott@diamond.ac.uk
author_name: Eva Lott
component_owner: ''
description: ''
distribution_name: event-model
docker: false
docs_type: sphinx
git_platform: github.com
github_org: bluesky
package_name: event_model
repo_name: event-model
