# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: dallan@bnl.gov
author_name: Brookhaven National Lab
description: Data model used by the bluesky ecosystem.
distribution_name: event-model
docker: false
docs_type: sphinx
git_platform: github.com
github_org: bluesky
package_name: event_model
pypi: true
repo_name: event-model
type_checker: mypy
