# ruff: noqa
# type: ignore
# generated by datamodel-codegen:
#   filename:  partial_resource.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel, Field


class PartialResource(BaseModel):
    spec: str = Field(..., title="spec")
    """
    String identifying the format/type of this Resource, used to identify a compatible Handler
    """
    resource_kwargs: Dict[str, Any] = Field(..., title="resource_kwargs")
    """
    Additional argument to pass to the Handler to read a Resource
    """
    resource_path: str = Field(..., title="resource_path")
    """
    Filepath or URI for locating this resource
    """
    root: str = Field(..., title="root")
    """
    Subset of resource_path that is a local detail, not semantic.
    """
    uid: str = Field(..., title="uid")
    """
    Globally unique identifier for this Resource
    """
