# ruff: noqa
# generated by datamodel-codegen:
#   filename:  datum_page.json

from __future__ import annotations

from typing import Dict, List, TypedDict

DataFrameForDatumPage = List[str]


class DatumPage(TypedDict):
    """
    Page of documents to reference a quanta of externally-stored data
    """

    datum_id: DataFrameForDatumPage
    """
    Array unique identifiers for each Datum (akin to 'uid' for other Document types), typically formatted as '<resource>/<integer>'
    """
    datum_kwargs: Dict[str, List]
    """
    Array of arguments to pass to the Handler to retrieve one quanta of data
    """
    resource: str
    """
    The UID of the Resource to which all Datums in the page belong
    """
