# ruff: noqa
# generated by datamodel-codegen:
#   filename:  datum.json

from __future__ import annotations

from typing import Any, Dict, TypedDict


class Datum(TypedDict):
    """
    Document to reference a quanta of externally-stored data
    """

    datum_id: str
    """
    Globally unique identifier for this Datum (akin to 'uid' for other Document types), typically formatted as '<resource>/<integer>'
    """
    datum_kwargs: Dict[str, Any]
    """
    Arguments to pass to the Handler to retrieve one quanta of data
    """
    resource: str
    """
    The UID of the Resource to which this Datum belongs
    """
