# ruff: noqa
# generated by datamodel-codegen:
#   filename:  resource.json
#   timestamp: 2024-12-18T10:56:19+00:00

from __future__ import annotations

from typing import Any, Dict, Literal, Optional, TypedDict

from typing_extensions import NotRequired


class Resource(TypedDict):
    """
    Document to reference a collection (e.g. file or group of files) of
    externally-stored data
    """

    path_semantics: NotRequired[Optional[Literal['posix', 'windows']]]
    """
    Rules for joining paths
    """
    resource_kwargs: Dict[str, Any]
    """
    Additional argument to pass to the Handler to read a Resource
    """
    resource_path: str
    """
    Filepath or URI for locating this resource
    """
    root: str
    """
    Subset of resource_path that is a local detail, not semantic.
    """
    run_start: NotRequired[Optional[str]]
    """
    Globally unique ID to the run_start document this resource is associated with.
    """
    spec: str
    """
    String identifying the format/type of this Resource, used to identify a compatible Handler
    """
    uid: str
    """
    Globally unique identifier for this Resource
    """
