# ruff: noqa
# generated by datamodel-codegen:
#   filename:  run_stop.json
#   timestamp: 2024-12-18T11:01:13+00:00

from __future__ import annotations

from typing import Any, Dict, Literal, Optional, TypedDict

from typing_extensions import NotRequired

DataType = Any


class RunStop(TypedDict):
    """
    Document for the end of a run indicating the success/fail state of the
    run and the end time
    """

    data_type: NotRequired[Optional[DataType]]
    """
    data_type
    """
    exit_status: Literal['success', 'abort', 'fail']
    """
    State of the run when it ended
    """
    num_events: NotRequired[Optional[Dict[str, int]]]
    """
    Number of Events per named stream
    """
    reason: NotRequired[Optional[str]]
    """
    Long-form description of why the run ended
    """
    run_start: str
    """
    Reference back to the run_start document that this document is paired with.
    """
    time: float
    """
    The time the run ended. Unix epoch
    """
    uid: str
    """
    Globally unique ID for this document
    """
