# generated by datamodel-codegen:
#   filename:  run_start.json
#   timestamp: 2024-12-17T17:00:12+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

from typing_extensions import NotRequired


class Calculation(TypedDict):
    args: Optional[List]
    callable: str
    """
    callable function to perform calculation
    """
    kwargs: NotRequired[Optional[Dict[str, Any]]]
    """
    kwargs for calcalation callable
    """


DataType = Any


class Hints(TypedDict):
    """
    Start-level hints
    """

    dimensions: NotRequired[Optional[List[List[Union[List[str], str]]]]]
    """
    The independent axes of the experiment. Ordered slow to fast
    """


class Projection(TypedDict):
    """
    Where to get the data from
    """

    calculation: NotRequired[Optional[Calculation]]
    """
    required fields if type is calculated
    """
    config_index: NotRequired[Optional[int]]
    config_device: NotRequired[Optional[str]]
    field: NotRequired[Optional[str]]
    location: NotRequired[Optional[Literal['start', 'event', 'configuration']]]
    """
    start comes from metadata fields in the start document, event comes from event, configuration comes from configuration fields in the event_descriptor document
    """
    stream: NotRequired[Optional[str]]
    type: NotRequired[Optional[Literal['linked', 'calculated', 'static']]]
    """
    linked: a value linked from the data set, calculated: a value that requires calculation, static:  a value defined here in the projection 
    """
    value: NotRequired[Any]
    """
    value explicitely defined in the projection when type==static.
    """


class Projections(TypedDict):
    """
    Describe how to interperet this run as the given projection
    """

    configuration: Dict[str, Any]
    """
    Static information about projection
    """
    name: NotRequired[Optional[str]]
    """
    The name of the projection
    """
    projection: Dict[str, Projection]
    version: str
    """
    The version of the projection spec. Can specify the version of an external specification.
    """


class RunStart(TypedDict):
    """
    Document created at the start of run. Provides a seach target and
    later documents link to it
    """

    data_groups: NotRequired[Optional[List[str]]]
    """
    An optional list of data access groups that have meaning to some external system. Examples might include facility, beamline, end stations, proposal, safety form.
    """
    data_session: NotRequired[Optional[str]]
    """
    An optional field for grouping runs. The meaning is not mandated, but this is a data management grouping and not a scientific grouping. It is intended to group runs in a visit or set of trials.
    """
    data_type: NotRequired[Optional[DataType]]
    group: NotRequired[Optional[str]]
    """
    Unix group to associate this data with
    """
    hints: NotRequired[Optional[Hints]]
    """
    Start-level hints
    """
    owner: NotRequired[Optional[str]]
    """
    Unix owner to associate this data with
    """
    project: NotRequired[Optional[str]]
    """
    Name of project that this run is part of
    """
    projections: NotRequired[Optional[List[Projections]]]
    sample: NotRequired[Optional[Union[Dict[str, Any], str]]]
    """
    Information about the sample, may be a UID to another collection
    """
    scan_id: NotRequired[Optional[int]]
    """
    Scan ID number, not globally unique
    """
    time: float
    """
    Time the run started.  Unix epoch time
    """
    uid: str
    """
    Globally unique ID for this run
    """
