name: Docs CI

on:
  push:
  pull_request:

jobs:
  docs:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: startsWith(github.ref, 'refs/tags')
        run: sleep 60

      - name: Install python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        # Can delete this if you don't use graphviz in your docs
        run: sudo apt-get install graphviz

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          touch requirements_dev.txt
          pip install -r requirements_dev.txt -e .[dev]

      - name: Build docs
        run: tox -e docs

      - name: Move to versioned directory
        # e.g. main or 0.1.2
        run: mv build/html ".github/pages/${{ github.ref_name }}"

      - name: Write switcher.json
        run: python .github/pages/make_switcher.py --add "${{ github.ref_name }}" ${{ github.repository }} .github/pages/switcher.json

      - name: Publish Docs to gh-pages
        if: github.event_name == 'push'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true
