name: Link Check

on:
  schedule:
    # Run every Monday at 8am to check URL links still resolve
    - cron: "0 8 * * WED"

jobs:
  docs:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          touch requirements_dev.txt
          pip install -r requirements_dev.txt -e .[dev]

      - name: Check links
        run: tox -e docs -- -b linkcheck
